// Corpus curé à la main pour un public scolaire (TXT-8) : mots courants et phrases neutres.
// Mots en minuscules, sans apostrophe ni trait d'union ; phrases avec majuscule et ponctuation.
import type { TextLanguage } from '@/components/lobbies/lobbySearch';

export const WORDS: Record<TextLanguage, readonly string[]> = {
  en: [
    'the', 'and', 'for', 'with', 'from', 'into', 'over', 'under', 'about', 'after', 'before', 'while',
    'time', 'year', 'people', 'way', 'day', 'world', 'school', 'family', 'student', 'friend', 'story', 'river',
    'mountain', 'forest', 'ocean', 'island', 'garden', 'window', 'kitchen', 'table', 'chair', 'paper', 'pencil', 'letter',
    'number', 'question', 'answer', 'problem', 'idea', 'reason', 'moment', 'morning', 'evening', 'night', 'summer', 'winter',
    'light', 'sound', 'music', 'picture', 'colour', 'water', 'fire', 'stone', 'cloud', 'rain', 'wind', 'snow',
    'quick', 'slow', 'bright', 'quiet', 'strong', 'gentle', 'happy', 'brave', 'clever', 'simple', 'heavy', 'empty',
    'young', 'early', 'large', 'small', 'warm', 'cold', 'fresh', 'clear', 'sharp', 'round', 'whole', 'proud',
    'make', 'take', 'give', 'find', 'think', 'know', 'learn', 'teach', 'write', 'read', 'speak', 'listen',
    'build', 'carry', 'catch', 'climb', 'dance', 'dream', 'jump', 'laugh', 'paint', 'plant', 'travel', 'wonder',
    'keyboard', 'type', 'race', 'finish', 'start', 'speed', 'focus', 'practice', 'rhythm', 'level', 'score', 'team',
    'zero', 'zone', 'zebra', 'puzzle', 'prize', 'freeze', 'dozen', 'breeze', 'maze', 'lazy', 'size', 'amaze',
    'jacket', 'joke', 'journey', 'judge', 'juice', 'kind', 'knife', 'king', 'quest', 'queen', 'quite', 'quote',
    'value', 'voice', 'visit', 'village', 'wave', 'yellow', 'yard', 'yes', 'box', 'fox', 'next', 'extra',
  ],
  fr: [
    'le', 'la', 'les', 'un', 'une', 'des', 'avec', 'pour', 'dans', 'sur', 'sous', 'entre',
    'temps', 'jour', 'nuit', 'matin', 'soir', 'monde', 'ville', 'maison', 'jardin', 'fenêtre', 'table', 'chaise',
    'école', 'élève', 'classe', 'cahier', 'crayon', 'livre', 'lettre', 'histoire', 'question', 'réponse', 'problème', 'idée',
    'rivière', 'montagne', 'forêt', 'océan', 'île', 'nuage', 'pluie', 'vent', 'neige', 'soleil', 'lune', 'étoile',
    'lumière', 'musique', 'image', 'couleur', 'eau', 'feu', 'pierre', 'arbre', 'fleur', 'chemin', 'pont', 'route',
    'rapide', 'lent', 'calme', 'fort', 'doux', 'heureux', 'brave', 'simple', 'lourd', 'vide', 'jeune', 'grand',
    'petit', 'chaud', 'froid', 'frais', 'clair', 'rond', 'fier', 'joli', 'facile', 'drôle', 'sûr', 'prêt',
    'faire', 'prendre', 'donner', 'trouver', 'penser', 'savoir', 'apprendre', 'écrire', 'lire', 'parler', 'écouter', 'jouer',
    'construire', 'porter', 'courir', 'grimper', 'danser', 'rêver', 'sauter', 'rire', 'peindre', 'planter', 'voyager', 'chanter',
    'clavier', 'touche', 'course', 'départ', 'arrivée', 'vitesse', 'rythme', 'niveau', 'équipe', 'victoire', 'effort', 'élan',
    'zéro', 'zone', 'zèbre', 'gazon', 'onze', 'douze', 'treize', 'seize', 'bizarre', 'lézard', 'hasard', 'azur',
    'jupe', 'juste', 'kayak', 'kilo', 'quai', 'quatre', 'quand', 'quoi', 'voix', 'voyage', 'wagon', 'yeux',
    'âme', 'bâton', 'château', 'fête', 'tête', 'forêt', 'naïf', 'noël', 'cœur', 'sœur', 'œuf', 'où',
    'boîte', 'goût', 'août', 'mûr', 'piqûre', 'déjà', 'voilà', 'leçon', 'garçon', 'français', 'reçu', 'façon',
  ].filter((word, i, words) => words.indexOf(word) === i),
};

export const SENTENCES: Record<TextLanguage, readonly string[]> = {
  en: [
    'The river runs past the old mill and into the quiet valley.',
    'Every morning, the students meet in the garden before class.',
    'A good typist keeps a steady rhythm and looks at the screen.',
    'The fox jumped over the fence and vanished into the forest.',
    'We packed some bread, a map and two warm jackets for the trip.',
    'Clouds gathered over the mountain, so the climbers turned back.',
    'Practice a little every day, and your speed will grow.',
    'She wrote the answer on the board and smiled at the class.',
    'The library is open late on Fridays, even in winter.',
    'Can you hear the music coming from the house next door?',
    'The team trained hard all season and won the final race.',
    'Bright lanterns lit the path that led down to the harbour.',
    'He fixed the old bicycle with a wrench and a lot of patience.',
    'The museum shows paintings from many countries and centuries.',
    'Snow fell all night, and the whole town woke up in silence.',
    'Keep your fingers on the home row and breathe slowly.',
    'The baker opens his shop at six and sells warm bread.',
    'Our school garden grows beans, carrots and sunflowers.',
    'The ship sailed north until the coast was out of sight.',
    'Quiet minds often find the clearest answers.',
    'The puzzle had a thousand pieces, but they finished it.',
    'A zebra and a giraffe walked slowly across the dusty plain.',
    'Thank you for helping me carry these heavy boxes!',
    'When the bell rang, everyone rushed outside to play.',
  ],
  fr: [
    'La rivière coule près du vieux moulin et rejoint la vallée.',
    'Chaque matin, les élèves se retrouvent dans la cour avant le cours.',
    'Un bon dactylo garde un rythme régulier et regarde l\'écran.',
    'Le renard a sauté par-dessus la clôture et disparu dans la forêt.',
    'Nous avons pris du pain, une carte et deux manteaux pour le voyage.',
    'Les nuages couvraient la montagne, alors les grimpeurs ont fait demi-tour.',
    'Pratique un peu chaque jour, et ta vitesse va grandir.',
    'Elle a écrit la réponse au tableau et a souri à la classe.',
    'La bibliothèque ferme tard le vendredi, même en hiver.',
    'Entends-tu la musique qui vient de la maison voisine?',
    'L\'équipe s\'est entraînée toute la saison et a gagné la course.',
    'Des lanternes éclairaient le chemin qui descendait vers le port.',
    'Il a réparé le vieux vélo avec une clé et beaucoup de patience.',
    'Le musée montre des tableaux de nombreux pays et de plusieurs siècles.',
    'La neige est tombée toute la nuit et la ville s\'est réveillée en silence.',
    'Garde tes doigts sur la rangée de repos et respire lentement.',
    'Le boulanger ouvre sa boutique à six heures et vend du pain chaud.',
    'Le jardin de l\'école donne des haricots, des carottes et des tournesols.',
    'Le bateau a navigué vers le nord jusqu\'à perdre la côte de vue.',
    'Un esprit calme trouve souvent les réponses les plus claires.',
    'Le casse-tête avait mille pièces, mais ils l\'ont terminé.',
    'Un zèbre et une girafe marchaient lentement dans la plaine.',
    'Merci de m\'aider à porter ces boîtes si lourdes!',
    'Quand la cloche a sonné, tout le monde a couru dehors pour jouer.',
  ],
};
